# Generated by Django 3.2.7 on 2022-09-07 01:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vpn_subscription', '0007_alter_vpnsubscription_reminder_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sevenDaysReminder', 'Seven Days Reminder'), ('threeDaysReminder', 'Three Days Reminder'), ('oneDayReminder', 'One Day Reminder'), ('subscriptionOutdated', 'Subscription Outdated')], max_length=150, verbose_name='Notification status')),
                ('was_sent', models.BooleanField(default=False)),
                ('vpn_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vpn_subscription.vpnsubscription')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
