"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import unittest

import xkcd_client
from xkcd_client.api.api_api import ApiApi  # noqa: E501


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_bot_user(self):
        """Test case for create_bot_user

        """
        pass

    def test_create_token_obtain_pair(self):
        """Test case for create_token_obtain_pair

        """
        pass

    def test_create_token_refresh(self):
        """Test case for create_token_refresh

        """
        pass

    def test_create_vpn_country(self):
        """Test case for create_vpn_country

        """
        pass

    def test_create_vpn_device_tariff(self):
        """Test case for create_vpn_device_tariff

        """
        pass

    def test_create_vpn_duration_price(self):
        """Test case for create_vpn_duration_price

        """
        pass

    def test_create_vpn_item(self):
        """Test case for create_vpn_item

        """
        pass

    def test_create_vpn_protocol(self):
        """Test case for create_vpn_protocol

        """
        pass

    def test_create_vpn_subscription(self):
        """Test case for create_vpn_subscription

        """
        pass

    def test_destroy_vpn_country(self):
        """Test case for destroy_vpn_country

        """
        pass

    def test_destroy_vpn_device_tariff(self):
        """Test case for destroy_vpn_device_tariff

        """
        pass

    def test_destroy_vpn_duration_price(self):
        """Test case for destroy_vpn_duration_price

        """
        pass

    def test_destroy_vpn_item(self):
        """Test case for destroy_vpn_item

        """
        pass

    def test_destroy_vpn_protocol(self):
        """Test case for destroy_vpn_protocol

        """
        pass

    def test_destroy_vpn_subscription(self):
        """Test case for destroy_vpn_subscription

        """
        pass

    def test_list_bot_users(self):
        """Test case for list_bot_users

        """
        pass

    def test_list_vpn_countrys(self):
        """Test case for list_vpn_countrys

        """
        pass

    def test_list_vpn_device_tariffs(self):
        """Test case for list_vpn_device_tariffs

        """
        pass

    def test_list_vpn_duration_prices(self):
        """Test case for list_vpn_duration_prices

        """
        pass

    def test_list_vpn_items(self):
        """Test case for list_vpn_items

        """
        pass

    def test_list_vpn_protocols(self):
        """Test case for list_vpn_protocols

        """
        pass

    def test_list_vpn_subscriptions(self):
        """Test case for list_vpn_subscriptions

        """
        pass

    def test_partial_update_vpn_country(self):
        """Test case for partial_update_vpn_country

        """
        pass

    def test_partial_update_vpn_device_tariff(self):
        """Test case for partial_update_vpn_device_tariff

        """
        pass

    def test_partial_update_vpn_duration_price(self):
        """Test case for partial_update_vpn_duration_price

        """
        pass

    def test_partial_update_vpn_item(self):
        """Test case for partial_update_vpn_item

        """
        pass

    def test_partial_update_vpn_protocol(self):
        """Test case for partial_update_vpn_protocol

        """
        pass

    def test_partial_update_vpn_subscription(self):
        """Test case for partial_update_vpn_subscription

        """
        pass

    def test_retrieve_vpn_country(self):
        """Test case for retrieve_vpn_country

        """
        pass

    def test_retrieve_vpn_device_tariff(self):
        """Test case for retrieve_vpn_device_tariff

        """
        pass

    def test_retrieve_vpn_duration_price(self):
        """Test case for retrieve_vpn_duration_price

        """
        pass

    def test_retrieve_vpn_item(self):
        """Test case for retrieve_vpn_item

        """
        pass

    def test_retrieve_vpn_protocol(self):
        """Test case for retrieve_vpn_protocol

        """
        pass

    def test_retrieve_vpn_subscription(self):
        """Test case for retrieve_vpn_subscription

        """
        pass

    def test_update_vpn_country(self):
        """Test case for update_vpn_country

        """
        pass

    def test_update_vpn_device_tariff(self):
        """Test case for update_vpn_device_tariff

        """
        pass

    def test_update_vpn_duration_price(self):
        """Test case for update_vpn_duration_price

        """
        pass

    def test_update_vpn_item(self):
        """Test case for update_vpn_item

        """
        pass

    def test_update_vpn_protocol(self):
        """Test case for update_vpn_protocol

        """
        pass

    def test_update_vpn_subscription(self):
        """Test case for update_vpn_subscription

        """
        pass


if __name__ == '__main__':
    unittest.main()
