"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import xkcd_client
from xkcd_client.model.token_obtain_pair import TokenObtainPair


class TestTokenObtainPair(unittest.TestCase):
    """TokenObtainPair unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenObtainPair(self):
        """Test TokenObtainPair"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenObtainPair()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
