"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import xkcd_client
from xkcd_client.model.vpn_item_instance_data_country_data import VpnItemInstanceDataCountryData


class TestVpnItemInstanceDataCountryData(unittest.TestCase):
    """VpnItemInstanceDataCountryData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpnItemInstanceDataCountryData(self):
        """Test VpnItemInstanceDataCountryData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VpnItemInstanceDataCountryData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
