"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import xkcd_client
from xkcd_client.model.vpn_duration_price import VpnDurationPrice


class TestVpnDurationPrice(unittest.TestCase):
    """VpnDurationPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpnDurationPrice(self):
        """Test VpnDurationPrice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VpnDurationPrice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
