"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import xkcd_client
from xkcd_client.model.vpn_device_tariff_duration_data import VpnDeviceTariffDurationData
globals()['VpnDeviceTariffDurationData'] = VpnDeviceTariffDurationData
from xkcd_client.model.vpn_device_tariff import VpnDeviceTariff


class TestVpnDeviceTariff(unittest.TestCase):
    """VpnDeviceTariff unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpnDeviceTariff(self):
        """Test VpnDeviceTariff"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VpnDeviceTariff()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
