"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import xkcd_client
from xkcd_client.model.vpn_subscription_tariff_data import VpnSubscriptionTariffData
from xkcd_client.model.vpn_subscription_user_data import VpnSubscriptionUserData
from xkcd_client.model.vpn_subscription_vpn_items_inner import VpnSubscriptionVpnItemsInner
globals()['VpnSubscriptionTariffData'] = VpnSubscriptionTariffData
globals()['VpnSubscriptionUserData'] = VpnSubscriptionUserData
globals()['VpnSubscriptionVpnItemsInner'] = VpnSubscriptionVpnItemsInner
from xkcd_client.model.vpn_subscription import VpnSubscription


class TestVpnSubscription(unittest.TestCase):
    """VpnSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpnSubscription(self):
        """Test VpnSubscription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VpnSubscription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
