"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import xkcd_client
from xkcd_client.model.token_refresh import TokenRefresh


class TestTokenRefresh(unittest.TestCase):
    """TokenRefresh unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenRefresh(self):
        """Test TokenRefresh"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenRefresh()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
