"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import xkcd_client
from xkcd_client.model.vpn_country import VpnCountry


class TestVpnCountry(unittest.TestCase):
    """VpnCountry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpnCountry(self):
        """Test VpnCountry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VpnCountry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
