"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import xkcd_client
from xkcd_client.model.vpn_item_instance_data_protocols_data_inner import VpnItemInstanceDataProtocolsDataInner


class TestVpnItemInstanceDataProtocolsDataInner(unittest.TestCase):
    """VpnItemInstanceDataProtocolsDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpnItemInstanceDataProtocolsDataInner(self):
        """Test VpnItemInstanceDataProtocolsDataInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VpnItemInstanceDataProtocolsDataInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
