# Generated by Django 4.0.6 on 2022-07-20 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('e82a8b12-00bc-4451-b8a6-45da249228ee'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('language', models.CharField(max_length=2, verbose_name='Language')),
                ('role', models.CharField(choices=[('New', 'New')], default='New', max_length=20, verbose_name='Role')),
                ('user_name', models.CharField(max_length=200, verbose_name='User Name')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('is_bot_blocked', models.BooleanField(default=False, verbose_name='Is Bot Blocked by User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
