# Generated by Django 4.0.5 on 2022-07-30 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('0b49e9de-227f-4fe0-accf-c954552f5be1'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='User ID')),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='User Name')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Last Name')),
                ('is_bot_blocked', models.BooleanField(default=False, verbose_name='Is Bot Blocked by User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
