# Generated by Django 3.2.7 on 2022-08-25 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9402498b-8fd9-4612-af84-da42b75ff96b'), editable=False),
        ),
    ]
