# Generated by Django 4.0.5 on 2022-07-31 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='pkid',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cee887ee-9b23-48c6-9c2d-adf6daab8613'), editable=False),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='User ID'),
        ),
    ]
