# Generated by Django 4.0.5 on 2022-07-24 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0ee68bc-1e7b-4697-b8aa-db615ac09cb5'), editable=False),
        ),
    ]
