# Generated by Django 3.2.7 on 2022-08-26 00:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0002_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('645d4fbc-911d-4405-b89f-8ff736b8b7c7'), editable=False),
        ),
        migrations.AlterModelTable(
            name='referralitem',
            table='referral_items',
        ),
    ]
