# Generated by Django 4.0.5 on 2022-08-01 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0002_remove_botuser_pkid_alter_botuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7252787-3047-4f70-a50f-c3c3b53e88eb'), editable=False),
        ),
    ]
