# Generated by Django 4.0.5 on 2022-07-24 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0003_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f634ae99-6e5d-440c-a291-ce8f43a07cf3'), editable=False),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.BigIntegerField(verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_name',
            field=models.CharField(max_length=200, null=True, verbose_name='User Name'),
        ),
    ]
