# Generated by Django 4.0.5 on 2022-08-06 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0003_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae3858f2-c2ac-428d-81e7-ff21ab0f9775'), editable=False),
        ),
    ]
