# Generated by Django 3.2.7 on 2022-08-26 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0003_auto_20220826_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a0bf935-c37d-4e0a-b7db-40d05045b1c3'), editable=False),
        ),
    ]
