# Generated by Django 3.2.7 on 2022-08-27 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0004_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8bc9ba1-5913-4c42-b7dd-ca42cc2c8b6a'), editable=False),
        ),
    ]
