# Generated by Django 4.0.5 on 2022-07-24 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0004_alter_botuser_first_name_alter_botuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eff99476-bf0b-4292-87c3-629b2309236d'), editable=False),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='User Name'),
            preserve_default=False,
        ),
    ]
