# Generated by Django 4.0.5 on 2022-08-08 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0004_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('09c71a42-0fe0-4305-a856-b9edc96f3b68'), editable=False),
        ),
    ]
