# Generated by Django 3.2.7 on 2022-08-27 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0005_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0f32b56-692a-492b-95ea-48013fe9181d'), editable=False),
        ),
    ]
