# Generated by Django 3.2.7 on 2022-08-27 23:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0006_alter_botuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralitem',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b7e34a0-459f-4433-9387-3067a6a680a4'), editable=False),
        ),
    ]
