# Generated by Django 4.0.5 on 2022-07-26 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0007_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e242b3d9-7820-4f26-9293-a474ccef8f90'), editable=False),
        ),
    ]
