# Generated by Django 3.2.7 on 2022-08-27 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0007_auto_20220828_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a594e652-6a82-4c69-a56e-34df18b744e8'), editable=False),
        ),
    ]
