# Generated by Django 4.0.5 on 2022-08-12 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0009_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65495ad3-7c76-4a93-95ec-3685a7c0b61f'), editable=False),
        ),
    ]
