# Generated by Django 4.0.5 on 2022-07-26 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0009_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46b674d5-f4b8-4b22-b9a9-0c6b27799342'), editable=False),
        ),
    ]
