# Generated by Django 4.0.5 on 2022-08-13 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0010_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7555d782-6cb1-4c05-83be-ad650f2281cf'), editable=False),
        ),
    ]
