# Generated by Django 3.2.7 on 2022-08-21 13:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0011_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e16710d8-74ca-49aa-a3a3-cf8794444c2b'), editable=False),
        ),
        migrations.CreateModel(
            name='ReferralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated_reward', models.BooleanField(default=False, verbose_name='Is activated reward')),
                ('referral_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referrals', to='bot_users.botuser')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referral_item', to='bot_users.botuser')),
            ],
        ),
    ]
