# Generated by Django 3.2.7 on 2022-09-05 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0011_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c5e2d62-873e-4423-a77f-a722f453e530'), editable=False),
        ),
    ]
