# Generated by Django 3.2.7 on 2022-08-21 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0012_auto_20220821_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='referral_value',
            field=models.CharField(db_index=True, default='374738827aV323', max_length=50, unique=True, verbose_name='Referral value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66c67677-c074-406b-a829-655304d35541'), editable=False),
        ),
    ]
