# Generated by Django 3.2.7 on 2022-09-05 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0012_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74a58fc5-f845-4715-b31a-de30d4cc1d15'), editable=False),
        ),
    ]
