# Generated by Django 3.2.7 on 2022-09-06 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0013_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('686dea14-cfab-4821-91ab-c4a381e64c4b'), editable=False),
        ),
    ]
