# Generated by Django 3.2.7 on 2022-08-23 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0013_auto_20220821_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9b93b92-21d4-4ab9-89b7-4eef0901baf8'), editable=False),
        ),
    ]
