# Generated by Django 4.0.5 on 2022-07-27 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0013_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90bf23d8-16ac-4232-810a-7e4637573936'), editable=False),
        ),
    ]
