# Generated by Django 3.2.7 on 2022-08-23 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0014_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e84494aa-843d-411b-b5b3-776f6e1961c3'), editable=False),
        ),
    ]
