# Generated by Django 3.2.7 on 2022-08-23 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0015_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d0b720f-44c8-48e5-beb5-87ddc239f5e6'), editable=False),
        ),
    ]
