# Generated by Django 3.2.7 on 2022-08-25 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0016_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8863b316-58b6-4a3b-bb6a-73e940f38037'), editable=False),
        ),
    ]
