# Generated by Django 3.2.7 on 2022-09-07 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0016_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bc89013-8d6a-4321-a807-456fd7a81456'), editable=False),
        ),
    ]
