# Generated by Django 4.0.5 on 2022-07-27 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0016_alter_botuser_id_alter_botuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6ca1e68-d406-4ff1-8941-186bb1133180'), editable=False),
        ),
    ]
