# Generated by Django 3.2.7 on 2022-09-17 21:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0018_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d95b0eea-d198-4c51-87f7-43a874774bc6'), editable=False),
        ),
        migrations.AlterField(
            model_name='referralitem',
            name='referral_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='bot_users.botuser'),
        ),
        migrations.AlterField(
            model_name='referralitem',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_item', to='bot_users.botuser'),
        ),
    ]
