# Generated by Django 4.0.5 on 2022-07-27 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0018_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d3d5601-03eb-494e-90ad-cef82e6ad73c'), editable=False),
        ),
    ]
