# Generated by Django 3.2.7 on 2022-08-25 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0018_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('898d968c-2a27-45c6-a75c-e8993f75bf29'), editable=False),
        ),
    ]
