# Generated by Django 3.2.7 on 2022-08-25 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0019_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6427ccda-9b0e-4ffe-9c6f-cba1ba985134'), editable=False),
        ),
    ]
