# Generated by Django 4.0.5 on 2022-07-27 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0019_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f77faf8-6f38-423b-b79c-e3909182c04e'), editable=False),
        ),
    ]
