# Generated by Django 4.0.5 on 2022-07-27 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0021_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a501b9c-6290-4f20-b146-aa6f0510f16a'), editable=False),
        ),
    ]
