# Generated by Django 4.0.5 on 2022-07-27 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0022_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20d2f803-9255-4a96-a163-85f38441b2c9'), editable=False),
        ),
    ]
