# Generated by Django 4.0.5 on 2022-07-28 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0023_alter_botuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('027789fe-1370-48b0-844b-878d6f5664a9'), editable=False),
        ),
    ]
