# Generated by Django 4.0.5 on 2022-07-28 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0024_alter_botuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='language',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('098f90b6-7d22-4a63-9c13-c5eabf001bd9'), editable=False),
        ),
    ]
