# Generated by Django 4.1 on 2022-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=32)),
                ('user_message', models.TextField()),
                ('status', models.BooleanField(null=True)),
                ('receive_date', models.DateTimeField()),
                ('answer_date', models.DateTimeField(blank=True, null=True)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('admin_message_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['status', '-receive_date'],
            },
        ),
    ]
