# Generated by Django 3.2.7 on 2022-08-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_feedback', '0002_alter_message_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='feedback_messages',
        ),
    ]
