# Generated by Django 3.2.7 on 2022-08-28 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0010_alter_botuser_id'),
        ('bot_feedback', '0003_alter_message_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_name',
        ),
        migrations.AddField(
            model_name='message',
            name='consumer',
            field=models.ForeignKey(default=395040322, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedback_messages', to='bot_users.botuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='receive_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
