version: "3.7"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        environment:
            - PG_PORT=5432
            - PG_HOST=postgres-db
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - postgres-db
        networks:
            - estate-react

    client:
        build:
            context: ./client
            dockerfile: ./docker/local/Dockerfile
        restart: on-failure
        volumes:
            - ./client:/app
            - /app/node_modules
        networks:
            - estate-react

    postgres-db:
        image: postgres:13.3
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file: .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5433:5432"
        networks:
            - estate-react

    nginx:
        restart: always
        depends_on:
            - api
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        build:
            context: ./docker/local/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        networks:
            - estate-react

networks:
    estate-react:
        driver: bridge

volumes:
    postgres_data:
    static_volume:
    media_volume: