version: "3.7"

services:

  nginx:
    image: vpn-dion-nginx
    build: ./docker/local/nginx

  bot:
    image: vpn-dion-bot
    build: 
      dockerfile: ./docker/local/bot/bot.dockerfile
      context: ./

  admin:
    image: vpn-dion-bot-admin
    build:
      dockerfile: ./docker/local/django/Dockerfile
      context: ./

  webapp:
    image: vpn-dion-webapp
    build: 
      context: ./frontend/
      dockerfile: Dockerfile

