version: "3.7"

services:
  postgres-db:
        image: postgres:13.3
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file: .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5436:5432"

volumes:
  postgres_data: