# Generated by Django 4.0.5 on 2022-07-30 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vpn_instance', '__first__'),
        ('vpn_subscription', '0002_alter_vpnsubscription_id'),
        ('vpn_protocol', '0002_alter_vpnprotocol_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnItem',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('e6a5c434-c2b8-4189-93b7-d915794ffdc5'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('public_key', models.CharField(max_length=200, verbose_name='Public Key')),
                ('private_key', models.CharField(max_length=200, verbose_name='Private Key')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('dns', models.CharField(max_length=100, verbose_name='DNS')),
                ('preshared_key', models.CharField(max_length=100, verbose_name='Preshared key')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Endpoint')),
                ('allowed_ips', models.CharField(max_length=500, verbose_name="Allowed IP's")),
                ('config_name', models.CharField(max_length=200, verbose_name='Config Name')),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_items', to='vpn_instance.vpninstance')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_items', to='vpn_protocol.vpnprotocol')),
                ('vpn_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_items', to='vpn_subscription.vpnsubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
