# Generated by Django 3.2.7 on 2022-09-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnitem',
            name='status',
            field=models.CharField(default='preparing', max_length=100, verbose_name='Status'),
        ),
    ]
