# Generated by Django 4.0.5 on 2022-08-01 07:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0004_alter_vpnsubscription_id_and_more'),
        ('vpn_item', '0002_alter_vpnitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ae3a6b4-ad23-4372-ba98-25a65d5251c7'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnitem',
            name='vpn_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vpn_items', to='vpn_subscription.vpnsubscription'),
        ),
    ]
