# Generated by Django 4.0.5 on 2022-07-30 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnProtocol',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('bb020ca1-699b-4a0a-86c7-49756e42d4ec'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(choices=[('wireguard', 'Wireguard'), ('open_vpn', 'OpenVPN')], max_length=154, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
