# Generated by Django 4.0.5 on 2022-07-30 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_protocol', '0002_alter_vpnprotocol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnprotocol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10949904-cfcd-41d5-bb5e-b48d0d8993bd'), editable=False),
        ),
    ]
