# Generated by Django 4.0.5 on 2022-08-08 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_protocol', '0006_alter_vpnprotocol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnprotocol',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
