# Generated by Django 3.2.7 on 2022-08-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_protocol', '0007_alter_vpnprotocol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnprotocol',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is default'),
        ),
    ]
