# Generated by Django 3.2.7 on 2022-08-26 23:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnsubscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='vpnsubscription',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='vpnsubscription',
            name='sign',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sign'),
        ),
    ]
