# Generated by Django 4.0.5 on 2022-07-31 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0002_alter_vpnsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7adb21c-ab71-4183-9ffa-ac3669be5173'), editable=False),
        ),
    ]
