# Generated by Django 3.2.7 on 2022-08-27 09:04

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0002_auto_20220827_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnsubscription',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vpnsubscription',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vpnsubscription',
            name='sign',
        ),
        migrations.CreateModel(
            name='VpnPaymentTransaction',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone')),
                ('sign', models.CharField(max_length=200, verbose_name='Sign')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency_id', models.CharField(max_length=50, verbose_name='Currency ID')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='vpn_subscription.vpnsubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
