# Generated by Django 3.2.7 on 2022-08-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0003_auto_20220827_1204'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vpnpaymenttransaction',
            table='vpn_payment_transaction',
        ),
    ]
