# Generated by Django 3.2.7 on 2022-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0005_auto_20220828_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnsubscription',
            name='reminder_state',
            field=models.IntegerField(choices=[('3', 'Reminded for three days'), ('7', 'Reminded for seven days'), ('1', 'Reminded for one day'), ('0', 'Ended')], default=7, verbose_name='Reminder status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('waiting for payment', 'Waiting for payment'), ('payment_was_failed', 'Payment was failed'), ('outdated', 'Outdated')], max_length=100, verbose_name='Subscription status'),
        ),
    ]
