# Generated by Django 4.0.5 on 2022-08-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0006_alter_vpnsubscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnsubscription',
            name='discount',
        ),
    ]
