# Generated by Django 3.2.7 on 2022-09-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0007_alter_vpnsubscription_reminder_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnpaymenttransaction',
            name='promocode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Promocode'),
        ),
    ]
