# Generated by Django 4.0.5 on 2022-08-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0007_remove_vpnsubscription_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnsubscription',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='vpnsubscription',
            name='total_price_currency',
        ),
    ]
