# Generated by Django 3.2.7 on 2022-09-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0008_vpnpaymenttransaction_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsubscription',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('waiting for payment', 'Waiting for payment'), ('payment_was_failed', 'Payment was failed'), ('outdated', 'Outdated'), ('defective', 'Defective')], max_length=100, verbose_name='Subscription status'),
        ),
    ]
