# Generated by Django 3.2.7 on 2022-08-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0008_remove_vpnsubscription_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnsubscription',
            name='is_referral',
            field=models.BooleanField(default=False, verbose_name='Is referral'),
        ),
    ]
