# Generated by Django 3.2.7 on 2022-08-23 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0009_vpnsubscription_is_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnsubscription',
            name='subscription_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End of subscription'),
            preserve_default=False,
        ),
    ]
