# Generated by Django 3.2.7 on 2022-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0009_alter_vpnsubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnpaymenttransaction',
            name='promocode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Promocode'),
        ),
    ]
