# Generated by Django 3.2.7 on 2022-08-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_subscription', '0011_auto_20220825_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnsubscription',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount percentage'),
        ),
    ]
