# Generated by Django 3.2.7 on 2022-08-25 23:39

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnCountry',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('place', django_countries.fields.CountryField(max_length=2, unique=True, verbose_name='Country')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='Country discount percentage')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default')),
            ],
            options={
                'verbose_name': 'Vpn country',
                'verbose_name_plural': 'Vpn Countries',
                'db_table': 'vpn_countries',
            },
        ),
    ]
