# Generated by Django 4.0.5 on 2022-07-30 10:16

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnCountry',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('a90160bc-2ec7-41a7-8507-d56942a06b58'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('place', django_countries.fields.CountryField(max_length=2, unique=True, verbose_name='Country')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='Country discount percentage')),
            ],
            options={
                'verbose_name': 'Vpn country',
                'verbose_name_plural': 'Vpn Countries',
            },
        ),
    ]
