# Generated by Django 4.0.5 on 2022-08-08 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_country', '0004_alter_vpncountry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
