# Generated by Django 3.2.7 on 2022-08-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_country', '0005_alter_vpncountry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpncountry',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is defauls'),
        ),
    ]
