# Generated by Django 3.2.7 on 2022-08-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_country', '0006_vpncountry_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpncountry',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is default'),
        ),
    ]
