# Generated by Django 4.0.5 on 2022-07-30 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vpn_country', '__first__'),
        ('vpn_protocol', '0003_alter_vpnprotocol_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnInstance',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('10949904-cfcd-41d5-bb5e-b48d0d8993bd'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('is_online', models.BooleanField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_instances', to='vpn_country.vpncountry', verbose_name='Country')),
                ('protocols', models.ManyToManyField(related_name='instances', to='vpn_protocol.vpnprotocol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
