# Generated by Django 3.2.7 on 2022-08-25 23:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vpn_country', '0001_initial'),
        ('vpn_protocol', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnInstance',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('server_protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], max_length=5, verbose_name='Server protocol')),
                ('name', models.CharField(max_length=100)),
                ('mac', models.CharField(blank=True, max_length=200, verbose_name='MAC')),
                ('is_online', models.BooleanField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_instances', to='vpn_country.vpncountry', verbose_name='Country')),
                ('protocols', models.ManyToManyField(related_name='instances', to='vpn_protocol.VpnProtocol')),
            ],
            options={
                'db_table': 'vpn_instances',
            },
        ),
    ]
