# Generated by Django 4.0.5 on 2022-08-08 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_instance', '0004_vpninstance_port_alter_vpninstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpninstance',
            name='mac',
            field=models.CharField(blank=True, max_length=200, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='vpninstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
