# Generated by Django 4.0.5 on 2022-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_instance', '0005_vpninstance_mac_alter_vpninstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpninstance',
            name='server_protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=5, verbose_name='Server protocol'),
            preserve_default=False,
        ),
    ]
