# Generated by Django 3.2.7 on 2022-09-12 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnDurationPrice',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('month_duration', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Month duration')),
            ],
            options={
                'verbose_name': 'Vpn duration price',
                'verbose_name_plural': 'Vpn durations prices',
                'db_table': 'vpn_duration_prices',
                'get_latest_by': 'month_duration',
            },
        ),
        migrations.CreateModel(
            name='VpnDeviceTariff',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('devices_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of devices')),
                ('operation', models.CharField(choices=[('equal', '='), ('greater_than_or_equal', '>=')], max_length=30, verbose_name='Device operation')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='Discount percentage')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_subscriptions', to='vpn_tariffs.vpndurationprice', verbose_name='Duration')),
            ],
            options={
                'db_table': 'vpn_devices',
            },
        ),
    ]
