# Generated by Django 3.2.7 on 2022-09-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsubscription',
            name='promo_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vpn_subscriptions', to='vpn_order.promocode'),
        ),
    ]
