# Generated by Django 3.2.7 on 2022-09-12 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('456ee095-e255-4996-ae51-746b17a7adc0'), editable=False),
        ),
    ]
