# Generated by Django 3.2.7 on 2022-08-25 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLocale',
            fields=[
                ('alias', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message_locale',
            },
        ),
    ]
