# Generated by Django 4.0.5 on 2022-07-26 20:51

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnSubscriptionOffer',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('ec03e4c7-82e4-4b68-a43a-49de857232ad'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('month_duration', models.IntegerField()),
                ('devices_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of devices')),
                ('operation', models.CharField(choices=[('equal', '='), ('greater_than_or_equal', '>=')], max_length=30, verbose_name='Device operation')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='Discount percentage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
