# Generated by Django 4.0.5 on 2022-07-26 21:08

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnCountry',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('46b674d5-f4b8-4b22-b9a9-0c6b27799342'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='Country discount percentage')),
            ],
            options={
                'verbose_name': 'Vpn country',
                'verbose_name_plural': 'Vpn Countries',
            },
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount percentage'),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46b674d5-f4b8-4b22-b9a9-0c6b27799342'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='month_duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Month duration'),
        ),
    ]
