# Generated by Django 4.0.5 on 2022-07-26 21:23

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0002_vpncountry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnDurationPrice',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('b4e9fba5-43bc-472b-8289-44a3de01c39e'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('month_duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Month duration')),
            ],
            options={
                'verbose_name': 'Vpn duration price',
                'verbose_name_plural': 'Vpn durations prices',
                'get_latest_by': 'month_duration',
            },
        ),
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4e9fba5-43bc-472b-8289-44a3de01c39e'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4e9fba5-43bc-472b-8289-44a3de01c39e'), editable=False),
        ),
    ]
