# Generated by Django 4.0.5 on 2022-07-27 12:26

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0007_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpncountry',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, unique=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0ddb2cc-82b3-4fcf-bbbf-59bf0c005349'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0ddb2cc-82b3-4fcf-bbbf-59bf0c005349'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='month_duration',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Month duration'),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0ddb2cc-82b3-4fcf-bbbf-59bf0c005349'), editable=False),
        ),
    ]
