# Generated by Django 4.0.5 on 2022-07-27 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0008_alter_vpncountry_country_alter_vpncountry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6ca1e68-d406-4ff1-8941-186bb1133180'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6ca1e68-d406-4ff1-8941-186bb1133180'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6ca1e68-d406-4ff1-8941-186bb1133180'), editable=False),
        ),
    ]
