# Generated by Django 4.0.5 on 2022-07-27 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0009_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d9411b5-ba70-41f7-8739-340eefc3007a'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d9411b5-ba70-41f7-8739-340eefc3007a'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d9411b5-ba70-41f7-8739-340eefc3007a'), editable=False),
        ),
    ]
