# Generated by Django 4.0.5 on 2022-07-27 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0010_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnProtocol',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('1d3d5601-03eb-494e-90ad-cef82e6ad73c'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(choices=[('wireguard', 'Wireguard'), ('open_vpn', 'OpenVPN')], max_length=154, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d3d5601-03eb-494e-90ad-cef82e6ad73c'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d3d5601-03eb-494e-90ad-cef82e6ad73c'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d3d5601-03eb-494e-90ad-cef82e6ad73c'), editable=False),
        ),
    ]
