# Generated by Django 4.0.5 on 2022-07-27 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0012_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f846d5c-85b0-4d21-83fa-d8ccf401fbdf'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f846d5c-85b0-4d21-83fa-d8ccf401fbdf'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnprotocol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f846d5c-85b0-4d21-83fa-d8ccf401fbdf'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f846d5c-85b0-4d21-83fa-d8ccf401fbdf'), editable=False),
        ),
    ]
