# Generated by Django 4.0.5 on 2022-07-27 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0013_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnsubscriptionoffer',
            name='month_duration',
        ),
        migrations.AddField(
            model_name='vpnsubscriptionoffer',
            name='duration',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='vpn_subscriptions', to='bot_assets.vpndurationprice', verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a501b9c-6290-4f20-b146-aa6f0510f16a'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a501b9c-6290-4f20-b146-aa6f0510f16a'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnprotocol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a501b9c-6290-4f20-b146-aa6f0510f16a'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a501b9c-6290-4f20-b146-aa6f0510f16a'), editable=False),
        ),
    ]
