# Generated by Django 4.0.5 on 2022-07-27 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0014_remove_vpnsubscriptionoffer_month_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20d2f803-9255-4a96-a163-85f38441b2c9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20d2f803-9255-4a96-a163-85f38441b2c9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnprotocol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20d2f803-9255-4a96-a163-85f38441b2c9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20d2f803-9255-4a96-a163-85f38441b2c9'), editable=False),
        ),
    ]
