# Generated by Django 4.0.5 on 2022-07-28 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0015_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('027789fe-1370-48b0-844b-878d6f5664a9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('027789fe-1370-48b0-844b-878d6f5664a9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnprotocol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('027789fe-1370-48b0-844b-878d6f5664a9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('027789fe-1370-48b0-844b-878d6f5664a9'), editable=False),
        ),
    ]
