# Generated by Django 4.0.5 on 2022-07-28 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0016_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpncountry',
            name='id',
            field=models.UUIDField(default=uuid.UUID('098f90b6-7d22-4a63-9c13-c5eabf001bd9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpndurationprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('098f90b6-7d22-4a63-9c13-c5eabf001bd9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnprotocol',
            name='id',
            field=models.UUIDField(default=uuid.UUID('098f90b6-7d22-4a63-9c13-c5eabf001bd9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscriptionoffer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('098f90b6-7d22-4a63-9c13-c5eabf001bd9'), editable=False),
        ),
    ]
