# Generated by Django 4.0.5 on 2022-07-24 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_users', '0002_alter_botuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnSubscription',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('d0ee68bc-1e7b-4697-b8aa-db615ac09cb5'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('amount_of_devices', models.IntegerField()),
                ('amount_of_month', models.IntegerField(choices=[(1, 'One'), (3, 'Three'), (6, 'SIX'), (12, 'Twelve')], verbose_name='Amount of months')),
                ('subscription_datetime_utc', models.DateTimeField(verbose_name='Subscription date time')),
                ('currency', models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd')], max_length=10, verbose_name='Currency')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_subscriptions', to='bot_users.botuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
