# Generated by Django 4.0.5 on 2022-07-24 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6c00ef5f-616a-4378-adf2-2c7639a72e76'), editable=False),
        ),
    ]
