# Generated by Django 4.0.5 on 2022-07-24 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_vpnsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f634ae99-6e5d-440c-a291-ce8f43a07cf3'), editable=False),
        ),
    ]
