# Generated by Django 4.0.5 on 2022-07-24 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_vpnsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eff99476-bf0b-4292-87c3-629b2309236d'), editable=False),
        ),
    ]
