# Generated by Django 4.0.5 on 2022-07-24 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_vpnsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b68b242-6096-400d-9462-cf941680f76a'), editable=False),
        ),
    ]
