# Generated by Django 4.0.5 on 2022-07-26 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_vpnsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02b3ae78-ef36-40e4-9447-19820bee35b9'), editable=False),
        ),
    ]
