# Generated by Django 4.0.5 on 2022-07-27 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0005_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
        ('subscription', '0011_alter_vpnsubscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('4e1e0148-9481-46f4-a519-be3e9c2182bd'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('is_online', models.BooleanField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='bot_assets.vpncountry', verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e1e0148-9481-46f4-a519-be3e9c2182bd'), editable=False),
        ),
        migrations.CreateModel(
            name='VpnItem',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('4e1e0148-9481-46f4-a519-be3e9c2182bd'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('public_key', models.CharField(max_length=200, verbose_name='Public Key')),
                ('private_key', models.CharField(max_length=200, verbose_name='Private Key')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('dns', models.CharField(max_length=100, verbose_name='DNS')),
                ('preshared_key', models.CharField(max_length=100, verbose_name='Preshared key')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Endpoint')),
                ('allowed_ips', models.CharField(max_length=500, verbose_name="Allowed IP's")),
                ('config_name', models.CharField(max_length=200, verbose_name='Config Name')),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_items', to='subscription.instance')),
                ('vpn_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_items', to='subscription.vpnsubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
