# Generated by Django 4.0.5 on 2022-07-27 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_instance_alter_vpnsubscription_id_vpnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90bf23d8-16ac-4232-810a-7e4637573936'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90bf23d8-16ac-4232-810a-7e4637573936'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='amount_of_month',
            field=models.IntegerField(verbose_name='Amount of months'),
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('90bf23d8-16ac-4232-810a-7e4637573936'), editable=False),
        ),
    ]
