# Generated by Django 4.0.5 on 2022-07-27 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_remove_vpnsubscription_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0ddb2cc-82b3-4fcf-bbbf-59bf0c005349'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0ddb2cc-82b3-4fcf-bbbf-59bf0c005349'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0ddb2cc-82b3-4fcf-bbbf-59bf0c005349'), editable=False),
        ),
    ]
