# Generated by Django 4.0.5 on 2022-07-27 17:29

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_alter_instance_id_alter_vpnitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('wireguard', 'Wireguard'), ('open_vpn', 'OpenVPN')], max_length=32), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6ca1e68-d406-4ff1-8941-186bb1133180'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6ca1e68-d406-4ff1-8941-186bb1133180'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6ca1e68-d406-4ff1-8941-186bb1133180'), editable=False),
        ),
    ]
