# Generated by Django 4.0.5 on 2022-07-27 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0011_vpnprotocol_alter_vpncountry_id_and_more'),
        ('subscription', '0017_rename_labels_instance_protocol_alter_instance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d3d5601-03eb-494e-90ad-cef82e6ad73c'), editable=False),
        ),
        migrations.RemoveField(
            model_name='instance',
            name='protocol',
        ),
        migrations.AddField(
            model_name='instance',
            name='protocol',
            field=models.ManyToManyField(to='bot_assets.vpnprotocol'),
        ),
        migrations.AlterField(
            model_name='vpnitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d3d5601-03eb-494e-90ad-cef82e6ad73c'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d3d5601-03eb-494e-90ad-cef82e6ad73c'), editable=False),
        ),
    ]
