# Generated by Django 4.0.5 on 2022-07-27 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0013_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
        ('subscription', '0019_rename_protocol_instance_protocols_alter_instance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f846d5c-85b0-4d21-83fa-d8ccf401fbdf'), editable=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='protocols',
            field=models.ManyToManyField(related_name='instances', to='bot_assets.vpnprotocol'),
        ),
        migrations.AlterField(
            model_name='vpnitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f846d5c-85b0-4d21-83fa-d8ccf401fbdf'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f846d5c-85b0-4d21-83fa-d8ccf401fbdf'), editable=False),
        ),
    ]
