# Generated by Django 4.0.5 on 2022-07-28 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_assets', '0016_alter_vpncountry_id_alter_vpndurationprice_id_and_more'),
        ('subscription', '0022_alter_instance_id_alter_vpnitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnitem',
            name='protocol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='vpn_items', to='bot_assets.vpnprotocol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('027789fe-1370-48b0-844b-878d6f5664a9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('027789fe-1370-48b0-844b-878d6f5664a9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('027789fe-1370-48b0-844b-878d6f5664a9'), editable=False),
        ),
    ]
