# Generated by Django 4.0.5 on 2022-07-28 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0023_vpnitem_protocol_alter_instance_id_alter_vpnitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('098f90b6-7d22-4a63-9c13-c5eabf001bd9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('098f90b6-7d22-4a63-9c13-c5eabf001bd9'), editable=False),
        ),
        migrations.AlterField(
            model_name='vpnsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('098f90b6-7d22-4a63-9c13-c5eabf001bd9'), editable=False),
        ),
    ]
