# Generated by Django 4.0.5 on 2022-07-30 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vpn_duration_tariff', '0002_alter_vpndurationprice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnDeviceTariff',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('2889e949-04d0-4adf-85e8-aff4dfac3ab3'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('devices_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of devices')),
                ('operation', models.CharField(choices=[('equal', '='), ('greater_than_or_equal', '>=')], max_length=30, verbose_name='Device operation')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='Discount percentage')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_subscriptions', to='vpn_duration_tariff.vpndurationprice', verbose_name='Duration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
